backend:
  name: github
  repo: dwin94/felsberg-gartenbau

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Seiten
    files:
      - file: src/pages/index.md
        label: Homepage # Name in admin UI.
        name: homepage # Post type identifier, used in routes. Must be unique.
        fields:
          - { label: Template Key, name: templateKey, widget: hidden }
          - { label: Titel, name: title, widget: string, required: true }
          - { label: Seiteninhalt, name: 'html', widget: 'markdown' }

  - name: categoryPages
    label: KategorieSeiten
    folder: src/pages/categoryPages
    create: true
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: categoryPage,
        }
      - { label: Titel, name: title, widget: string }
      - {
          label: Kategorie auf Homepage,
          name: categoryOnHomepage,
          widget: boolean,
          default: false,
        }
      - {
          label: Link in Navigation,
          name: linkInNavigation,
          widget: boolean,
          default: false,
        }
      - { label: Bild, name: image, widget: image }
      - { label: Seiteninhalt, name: 'html', widget: 'markdown' }
